server:
  contextPath: /service
  port: 8080
logging:
  level:
    org.springframework: INFO
spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql/test
    username: test
    password: test 
spring.jpa:
  hibernate.ddl-auto: create
  database-platform: org.hibernate.dialect.MySQL5Dialect
info.build:
  artifact: "@project.artifactId@"
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@" 
         
    